# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - id: foo
        uses: luweilevi/test-ecr-sync@puppet
        with:
          image: "tradeshift-base/ada-coding:d1ef816a25d782e3aad48fe82e816a14231da771"
          target-image: "test/ada:latest"
          source-repo: tradeshift-registry.cn-shanghai.cr.aliyuncs.com
          target-repo: 121118285438.dkr.ecr.cn-northwest-1.amazonaws.com.cn
          cn_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          cn_access_secret: ${{ secrets.AWS_ACCESS_SECRET }}
          
