on:
  push:
  issue_comment:
    types: [created, edited]

jobs:
  docker-push:
  #  if: (contains(github.event.comment.body, 'push') || contains(github.event.comment.body, 'deploy rise')) && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.issue.pull_request}}++++${{github.event.comment.body}}"
      - run: echo "${{github.event.comment.html_url}}"
  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job-b"
      - run: exit 1
  job-c:
    runs-on: ubuntu-latest
    needs: [docker-push, job-b]
    steps:
      - name: run
        if: ${{ needs.job-b.result != 'success' }}
      - run: echo "this is job-C"
    
