on:
  issue_comment:
    types: [created, edited]

jobs:
  docker-push:
    if: (contains(github.event.comment.body, 'push') || contains(github.event.comment.body, 'deploy rise')) && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.issue.pull_request}}++++${{github.event.comment.body}}"
