on:
  issue_comment:
    types: [created, edited]

jobs:
  docker-push:
    if: (contains(github.event.comment.body, 'push') || contains(github.event.comment.body, 'deploy rise')) && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{github.event.issue.pull_request}}++++${{github.event.comment.body}}"
      - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - run: echo '{"name":"docker-push","head_sha":"${{ github.sha }}","conclusion":"success"}' | gh api /repos/luweilevi/test/check-runs --input -

